import { PART_OF_SPEECH } from '../../constants/part-of-speech.constant';
import { TYPE_CONDITION } from '../../constants/type-condition.constant';
import { type Options } from './parts-of-speech.options';

export const PARTS_OF_SPEECH_DEFAULT: Options = {
  dictionary: {
    verb: [
      'noop',
      'reset',
      'toggle',
      'open',
      'close',
      'clear',
      'cleanup',
      'setup',
      'select',
      'unselect',
      'expand',
      'collapse',
      'mark',
      'logout',
      'enqueue',
      'redirect',
      'cache'
    ],
    noun: [
      'manifest',
      'message',
      'target',
      'model',
      'binary',
      'kind',
      'package',
      'prefix',
      'request',
      'state',
      'sort',
      'position',
      'plan',
      'plane',
      'touch',
      'token',
      'base',
      'release',
      'fragment',
      'attribute',
      'content',
      'offset',
      'order',
      'name',
      'format',
      'import',
      'export',
      'override',
      'change',
      'call',
      'predicate',
      'type',
      'value',
      'variable',
      'key',
      'reference',
      'link',
      'index',
      'like',
      'match',
      'log',
      'promise',
      'limit',
      'invite',
      'abort',
      'code',
      'guard',
      'survey',
      'seat',
      'rect',
      'delay',
      'frame',
      'rate',
      'warning',
      'heading',
      'list',
      'focus',
      'variant',
      'secret',
      'scene',
      'zoom',
      'date',
      'count',
      'start',
      'end',
      'test',
      'record',
      'screen',
      'exit',
      'age',
      'view',
      'buffer',
      'overflow',
      'draw',
      'pull',
      'share',
      'save',
      'search',
      'fix',
      'filter',
      'update',
      'edit',
      'refresh',
      'fade',
      'flash',
      'freeze',
      'chat',
      'support',
      'detail',
      'backend',
      'frontend',
      'blockquote',
      'command',
      'question',
      'visit',
      'score',
      'reserve',
      'network',
      'conflict',
      'check',
      'float',
      'stage',
      'demo',
      'home',
      'handle',
      'drawing',
      'reason',
      'control',
      'set',
      'write',
      'read',
      'mismatch',
      'retry',
      'copy'
    ]
  },
  declarationPolicies: {
    variable: {
      [TYPE_CONDITION.Boolean]: { required: [PART_OF_SPEECH.Verb] },
      [TYPE_CONDITION.Function]: { required: [PART_OF_SPEECH.Verb] },
      default: { required: [PART_OF_SPEECH.Noun], restricted: [PART_OF_SPEECH.Verb] }
    },
    function: {
      default: { required: [PART_OF_SPEECH.Verb] }
    },
    class: {
      default: { required: [PART_OF_SPEECH.Noun] }
    },
    interface: {
      default: { required: [PART_OF_SPEECH.Noun] }
    },
    type: {
      default: { required: [PART_OF_SPEECH.Noun] }
    },
    enum: {
      default: { required: [PART_OF_SPEECH.Noun] }
    }
  }
};
